version: "3"
services:
  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
      - /myapp/vendor/bundle
      - /myapp/.bundle
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
    links:
      - db
      - redis
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
  db:
    image: postgres:12
    ports:
      - "5432:5433"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  redis:
    image: redis:5.0.6
    ports:
      - "6379:6379"
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/myapp
      - node_modules:/myapp/node_modules
    ports:
      - "8080:8080"
volumes:
  postgresql-data:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
